language: node_js

node_js:
    - '0.10'

before_install:
    - wget https://phantomjs.googlecode.com/files/phantomjs-1.9.1-linux-i686.tar.bz2
    - tar xjf phantomjs-1.9.1-linux-i686.tar.bz2
    - sudo ln -fs `pwd`/phantomjs-1.9.1-linux-i686/bin/phantomjs /usr/local/bin/phantomjs
    - git clone git://github.com/n1k0/casperjs.git ~/casperjs
    - cd ~/casperjs
    - git checkout tags/1.1-beta1
    - export PATH=$PATH:`pwd`/bin
    - cd -

before_script:
    - phantomjs --version
    - npm install -g grunt-cli

notifications:

    email: false

    irc:
        channels:
            - 'ircnet.eversible.com#codebrowser'
        on_success: never
        use_notice: true
        skip_join: true
        template:
            - '**'
            - '%{message}'
            - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{commit_message}'
            - 'Build details : %{build_url}'
            - '**'
