language: node_js

node_js:
    - '0.10'

before_script:
    - npm install -g grunt-cli

notifications:

    email: false

    irc:
        channels:
            - 'irc.nebula.fi#codebrowser'
        use_notice: true
        skip_join: true
