language: node_js

node_js:
    - '0.10'

branches:

    except:
        - demo

before_install:
    - git clone git://github.com/n1k0/casperjs.git ~/casperjs
    - cd ~/casperjs
    - git checkout tags/1.1-beta3
    - export PATH=$PATH:`pwd`/bin
    - cd -

before_script:
    - phantomjs --version
    - casperjs --version
    - npm install -g grunt-cli
    - npm install -d

notifications:

    email: false

    irc:
        channels:
            - 'ircnet.eversible.com#codebrowser'
        on_success: change
        use_notice: true
        skip_join: true
        template:
            - '**'
            - '%{message}'
            - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{commit_message}'
            - 'Build details : %{build_url}'
            - '**'
