language: node_js

node_js:
    - '0.10'

before_script:
    - npm install -g grunt-cli

notifications:

    email: false

    irc:
        channels:
            - 'ircnet.eversible.com#codebrowser'
        on_success: never
        use_notice: true
        skip_join: true
        template:
            - '**'
            - '%{message}'
            - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{commit_message}'
            - 'Build details : %{build_url}'
            - '**'
